Feature/views
TheLuisAbarca/RoR_Blog-App pull request #5
Opened 2022-03-30 22:44 UTC by TheLuisAbarca

## Views
> In this branch, I have made the following changes:

1. Implement necessary stylesheets to make the appearance similar to the views required.
2. Implement the controllers part with the necessary assignation of instance variables to be used on views.
3. Add a method to find an author of a comment.
4. Change the title of the App to be according to this project.
5. Add partials components and the corresponding views of posts and users that are relationated with routes.

2022-03-30 23:03 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-30 23:03 UTC, arslanbisharat commented on app/controllers/users_controller.rb
> +    # @posts = Post.where(author_id: params[:id]).order(:id)
- [ ] Let's remove the commented code. It makes code dirty and hard to read.

2022-03-30 23:03 UTC, arslanbisharat commented on app/controllers/users_controller.rb
> +  end
- [ ] #index should have User.all instead of  User.order(:id)

```ruby
 def index
      @users = User.all
    end
```

2022-03-31 00:55 UTC, TheLuisAbarca commented on app/controllers/users_controller.rb
> +  end
Hi @arslanbisharat, thanks for your kindly feedback. The issue is solved and implemented on commit 33556dc.

2022-03-31 00:55 UTC, TheLuisAbarca commented on app/controllers/users_controller.rb
> +    # @posts = Post.where(author_id: params[:id]).order(:id)
Hi @arslanbisharat, thanks for your kindly feedback. The issue is solved and implemented on commit 33556dc.

2022-03-31 01:00 UTC, MahmoudBakr23 approved these changes
Hi @TheLuisAbarca 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-31 01:07 UTC, merged